language: java
jdk:
  - oraclejdk8
branches:
  only:
  - master
env:
  global:
  - secure: "ezQL7lzQcdDiDT6ugrhnNUyvw7DG1g8qvdnPLWGHolyg60kxmvlngf596L3imwS6Itwoddj7MLTze2m+eLtYWonTN91vrPnEqM8Gu/eG7SAun+usJGLdQUZtgLvJi5WSmiuT5TsZcD8OT1UKlBPx5oc7lNafEILbc4aC/b7JcvGSusdLZeu42h+6+j185TN6q0ivst8YIuVeNzo6pp8tZyMXnKIBMkcSFDwigKc/EUqlF1LKyR7l0uM8ASd6sh9BL4+aTk8K6xSEWv82XpwIgzWrNPbRGD4V325aHJXvvm7uLWP72oU8MCOQ+MYvqjFgg8qcwTrVfnxucETyPVI6/vONo7sImAV2DdzZdahP4xmz4uV3I7CifINLZr9lAbARuaT+3ELo8aAK8VBZuncQ4EJ9YB9SP8dPNnKLulGiTswjuq95xAvBGSe+NdP7g2fDyKz9eZAdNK+58RBBPkCPNz38k2hQmHGh6dwVg9GRfRVZYRd5nN4Pl0jxFLeiLMlmHksvzqAPcri3tEEHjGBN0jJeHDz50IJdbJAB6OZyNkqnKmrtcc5ggB+N89ca5K5LVo3GOU+qDf2HY8lKpdYxWqwcFtWJYhvJsN/tWtHPkWZeYiQsftBZxCcKI4kW8PMnu98bESJsMyMAJ/PZe9iU/64wfdhO8EWREwnsK94VsD8="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "wultra/powerauth-admin"
      description: "Build submitted via Travis CI"
    notification_email: petr@wultra.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: develop
